<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Diocesi;

class DiocesiSeeder extends Seeder
{
    public function run(): void
    {
        $diocesi = [
            ['nome' => 'Acqui Terme', 'regione' => 'Piemonte'],
            ['nome' => 'Afragola', 'regione' => 'Campania'],
            ['nome' => 'Agrigento', 'regione' => 'Sicilia'],
            ['nome' => 'Alba', 'regione' => 'Piemonte'],
            ['nome' => 'Alessandria', 'regione' => 'Piemonte'],
            ['nome' => 'Ancona', 'regione' => 'Marche'],
            ['nome' => 'Aosta', 'regione' => 'Valle d\'Aosta'],
            ['nome' => 'Aquila', 'regione' => 'Abruzzo'],
            ['nome' => 'Arezzo', 'regione' => 'Toscana'],
            ['nome' => 'Ascoli Piceno', 'regione' => 'Marche'],
            ['nome' => 'Assisi', 'regione' => 'Umbria'],
            ['nome' => 'Asti', 'regione' => 'Piemonte'],
            ['nome' => 'Avellino', 'regione' => 'Campania'],
            ['nome' => 'Bari', 'regione' => 'Puglia'],
            ['nome' => 'Barletta', 'regione' => 'Puglia'],
            ['nome' => 'Belluno', 'regione' => 'Veneto'],
            ['nome' => 'Benevento', 'regione' => 'Campania'],
            ['nome' => 'Bergamo', 'regione' => 'Lombardia'],
            ['nome' => 'Biella', 'regione' => 'Piemonte'],
            ['nome' => 'Bologna', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Bolzano', 'regione' => 'Trentino-Alto Adige'],
            ['nome' => 'Brescia', 'regione' => 'Lombardia'],
            ['nome' => 'Brindisi', 'regione' => 'Puglia'],
            ['nome' => 'Cagliari', 'regione' => 'Sardegna'],
            ['nome' => 'Caltanissetta', 'regione' => 'Sicilia'],
            ['nome' => 'Campobasso', 'regione' => 'Molise'],
            ['nome' => 'Caserta', 'regione' => 'Campania'],
            ['nome' => 'Cassano allo Ionio', 'regione' => 'Calabria'],
            ['nome' => 'Castelvetrano', 'regione' => 'Sicilia'],
            ['nome' => 'Catania', 'regione' => 'Sicilia'],
            ['nome' => 'Catanzaro', 'regione' => 'Calabria'],
            ['nome' => 'Cefalù', 'regione' => 'Sicilia'],
            ['nome' => 'Cerro al Lambro', 'regione' => 'Lombardia'],
            ['nome' => 'Cesena', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Chieti', 'regione' => 'Abruzzo'],
            ['nome' => 'Civitavecchia', 'regione' => 'Lazio'],
            ['nome' => 'Cosenza', 'regione' => 'Calabria'],
            ['nome' => 'Cremona', 'regione' => 'Lombardia'],
            ['nome' => 'Crotone', 'regione' => 'Calabria'],
            ['nome' => 'Cuneo', 'regione' => 'Piemonte'],
            ['nome' => 'Donegal', 'regione' => 'Irlanda'],
            ['nome' => 'Enna', 'regione' => 'Sicilia'],
            ['nome' => 'Fano', 'regione' => 'Marche'],
            ['nome' => 'Fermo', 'regione' => 'Marche'],
            ['nome' => 'Ferrara', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Firenze', 'regione' => 'Toscana'],
            ['nome' => 'Foggia', 'regione' => 'Puglia'],
            ['nome' => 'Foligno', 'regione' => 'Umbria'],
            ['nome' => 'Forlì', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Frosinone', 'regione' => 'Lazio'],
            ['nome' => 'Genova', 'regione' => 'Liguria'],
            ['nome' => 'Gorizia', 'regione' => 'Friuli-Venezia Giulia'],
            ['nome' => 'Grosseto', 'regione' => 'Toscana'],
            ['nome' => 'Gubbio', 'regione' => 'Umbria'],
            ['nome' => 'Imola', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Isernia', 'regione' => 'Molise'],
            ['nome' => 'L\'Aquila', 'regione' => 'Abruzzo'],
            ['nome' => 'La Spezia', 'regione' => 'Liguria'],
            ['nome' => 'Lamezia Terme', 'regione' => 'Calabria'],
            ['nome' => 'Latina', 'regione' => 'Lazio'],
            ['nome' => 'Lecce', 'regione' => 'Puglia'],
            ['nome' => 'Lecco', 'regione' => 'Lombardia'],
            ['nome' => 'Livorno', 'regione' => 'Toscana'],
            ['nome' => 'Lodi', 'regione' => 'Lombardia'],
            ['nome' => 'Lucca', 'regione' => 'Toscana'],
            ['nome' => 'Lunedì', 'regione' => 'Marche'],
            ['nome' => 'Macerata', 'regione' => 'Marche'],
            ['nome' => 'Mantova', 'regione' => 'Lombardia'],
            ['nome' => 'Massa', 'regione' => 'Toscana'],
            ['nome' => 'Matera', 'regione' => 'Basilicata'],
            ['nome' => 'Messina', 'regione' => 'Sicilia'],
            ['nome' => 'Milano', 'regione' => 'Lombardia'],
            ['nome' => 'Modena', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Monaco', 'regione' => 'Germania'],
            ['nome' => 'Mongolia', 'regione' => 'Asia'],
            ['nome' => 'Monreale', 'regione' => 'Sicilia'],
            ['nome' => 'Montefeltro', 'regione' => 'Marche'],
            ['nome' => 'Montepulciano', 'regione' => 'Toscana'],
            ['nome' => 'Monza', 'regione' => 'Lombardia'],
            ['nome' => 'Napoli', 'regione' => 'Campania'],
            ['nome' => 'Novara', 'regione' => 'Piemonte'],
            ['nome' => 'Nuoro', 'regione' => 'Sardegna'],
            ['nome' => 'Oristano', 'regione' => 'Sardegna'],
            ['nome' => 'Otranto', 'regione' => 'Puglia'],
            ['nome' => 'Padova', 'regione' => 'Veneto'],
            ['nome' => 'Palermo', 'regione' => 'Sicilia'],
            ['nome' => 'Parma', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Pavia', 'regione' => 'Lombardia'],
            ['nome' => 'Perugia', 'regione' => 'Umbria'],
            ['nome' => 'Pesaro', 'regione' => 'Marche'],
            ['nome' => 'Piacenza', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Pisa', 'regione' => 'Toscana'],
            ['nome' => 'Pistoia', 'regione' => 'Toscana'],
            ['nome' => 'Pordenone', 'regione' => 'Friuli-Venezia Giulia'],
            ['nome' => 'Potenza', 'regione' => 'Basilicata'],
            ['nome' => 'Prato', 'regione' => 'Toscana'],
            ['nome' => 'Ragusa', 'regione' => 'Sicilia'],
            ['nome' => 'Ravenna', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Reggio Calabria', 'regione' => 'Calabria'],
            ['nome' => 'Reggio Emilia', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Rieti', 'regione' => 'Lazio'],
            ['nome' => 'Rimini', 'regione' => 'Emilia-Romagna'],
            ['nome' => 'Roma', 'regione' => 'Lazio'],
            ['nome' => 'Rosario', 'regione' => 'Argentina'],
            ['nome' => 'Rovigo', 'regione' => 'Veneto'],
            ['nome' => 'Salerno', 'regione' => 'Campania'],
            ['nome' => 'San Severo', 'regione' => 'Puglia'],
            ['nome' => 'Sassari', 'regione' => 'Sardegna'],
            ['nome' => 'Savona', 'regione' => 'Liguria'],
            ['nome' => 'Siena', 'regione' => 'Toscana'],
            ['nome' => 'Siracusa', 'regione' => 'Sicilia'],
            ['nome' => 'Sondrio', 'regione' => 'Lombardia'],
            ['nome' => 'Spezia', 'regione' => 'Liguria'],
            ['nome' => 'Spoleto', 'regione' => 'Umbria'],
            ['nome' => 'Syracuse', 'regione' => 'USA'],
            ['nome' => 'Taranto', 'regione' => 'Puglia'],
            ['nome' => 'Tempio Ampurias', 'regione' => 'Sardegna'],
            ['nome' => 'Teramo', 'regione' => 'Abruzzo'],
            ['nome' => 'Terni', 'regione' => 'Umbria'],
            ['nome' => 'Tirana', 'regione' => 'Albania'],
            ['nome' => 'Torino', 'regione' => 'Piemonte'],
            ['nome' => 'Tortona', 'regione' => 'Piemonte'],
            ['nome' => 'Trani', 'regione' => 'Puglia'],
            ['nome' => 'Trapani', 'regione' => 'Sicilia'],
            ['nome' => 'Trento', 'regione' => 'Trentino-Alto Adige'],
            ['nome' => 'Treviso', 'regione' => 'Veneto'],
            ['nome' => 'Trieste', 'regione' => 'Friuli-Venezia Giulia'],
            ['nome' => 'Udine', 'regione' => 'Friuli-Venezia Giulia'],
            ['nome' => 'Urbino', 'regione' => 'Marche'],
            ['nome' => 'Vaticano', 'regione' => 'Lazio'],
            ['nome' => 'Vercelli', 'regione' => 'Piemonte'],
            ['nome' => 'Verona', 'regione' => 'Veneto'],
            ['nome' => 'Vibo Valentia', 'regione' => 'Calabria'],
            ['nome' => 'Vicenza', 'regione' => 'Veneto'],
            ['nome' => 'Viterbo', 'regione' => 'Lazio'],
            ['nome' => 'Vittorio Veneto', 'regione' => 'Veneto'],
        ];

        foreach ($diocesi as $d) {
            Diocesi::create($d);
        }
    }
}